# ---------- Compiler ----------
COMMON_FLAGS="-march=sandybridge -O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

# ---------- Parallelism ----------
MAKEOPTS="-j4 -l4"
EMERGE_DEFAULT_OPTS="--jobs=3 --load-average=4"

# ---------- Language ----------
LC_MESSAGES=C.utf8

# ---------- Portage ----------
PORTDIR="/var/db/repos/gentoo"
DISTDIR="/var/cache/distfiles"
PKGDIR="/var/cache/binpkgs"

# ---------- USE flags ----------
USE="
-X -wayland
-opengl -vulkan
-pipewire -sound -alsa -pulseaudio -screencast
zstd
udev dbus
-openrc
-gnome -kde
"

# ---------- ABI ----------
ABI_X86="64"

# ---------- Keywords ----------
ACCEPT_KEYWORDS="amd64"

# ---------- Licenses ----------
ACCEPT_LICENSE="*"

# ---------- CPU microcode ----------
MICROCODE_SIGNATURES="intel"
